# Generated by Django 3.2.2 on 2022-03-08 12:11

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfollowing',
            name='unique_followers',
        ),
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.UniqueConstraint(condition=models.Q(('user', django.db.models.expressions.F(
                'followed_user')), _negated=True), fields=('user', 'followed_user'), name='unique_followers'),
        ),
    ]
