# Generated by Django 3.2.2 on 2022-03-22 22:04

from django.db import migrations

import account.models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", account.models.CustomUserManager()),
            ],
        ),
    ]
