version: 2.2
jobs:
    build:
        docker:
            - image: cimg/python:3.10.1
        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - run:
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
                paths:
                    - "venv"
            - run:
                name: Runing static tests
                command: |
                    . venv/bin/activate
                    pre-commit run --all-files
            - run:
                name: Running unit tests
                command: |
                    . venv/bin/activate
                    pytest
            - store_artifacts:
                path: test-reports/
                destination: habbit-ci
