# Generated by Django 3.2.2 on 2022-03-27 11:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import thread.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=datetime.datetime(
                    2022, 3, 27, 11, 19, 41, 842011, tzinfo=utc))),
                ('file', models.FileField(upload_to='media/attachement/', validators=[
                 thread.validators.file_size_validator, thread.validators.file_type_validator])),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=datetime.datetime(
                    2022, 3, 27, 11, 19, 41, 843196, tzinfo=utc))),
                ('content', models.TextField(blank=True, null=True)),
                ('edited', models.BooleanField(default=True)),
                ('date_edited', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(to='thread.Attachment')),
                ('created_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
