# Generated by Django 3.2.2 on 2022-03-27 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='date_created',
            field=models.DateTimeField(auto_created=datetime.datetime(
                2022, 3, 27, 11, 34, 13, 776678, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_created=datetime.datetime(
                2022, 3, 27, 11, 34, 13, 777782, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
