# Generated by Django 3.2.2 on 2022-03-27 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_auto_20220327_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='date_created',
            field=models.DateTimeField(auto_created=datetime.datetime(
                2022, 3, 27, 11, 36, 13, 952328, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='thread.Attachment'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_created=datetime.datetime(
                2022, 3, 27, 11, 36, 13, 953545, tzinfo=utc)),
        ),
    ]
