# Generated by Django 3.2.2 on 2022-03-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_auto_20220327_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
