# Generated by Django 3.2.2 on 2022-04-02 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thread', '0004_auto_20220327_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[
                 (0, 'Music Thread'), (1, 'Photo Thread'), (2, 'Post Thread')], default=2, max_length=250)),
                ('reply_setting', models.CharField(choices=[(0, 'Allow all user to reply'), (
                    1, 'Allow only followers to reply'), (2, 'Allow only mentiond users to reply')], default=0, max_length=250)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message', models.OneToOneField(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to='thread.message')),
                ('replying', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                               related_name='replies', to='thread.thread')),
                ('sharing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='shares', to='thread.thread')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddConstraint(
            model_name='thread',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('replying__isnull', True), ('sharing__isnull', False)), models.Q(('replying__isnull', False), ('sharing__isnull', True)), models.Q(
                ('replying__isnull', True), ('sharing__isnull', True)), _connector='OR'), name="thread_thread_can't set sharing field and replying field at the same time"),
        ),
        migrations.AddConstraint(
            model_name='thread',
            constraint=models.CheckConstraint(check=models.Q(('message__isnull', False), (
                'replying__isnull', False)), name='thread_thread_message field can not be null in reply thread'),
        ),
    ]
