# Generated by Django 3.2.2 on 2022-04-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0005_auto_20220402_1024'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='thread',
            name='thread_thread_message field can not be null in reply thread',
        ),
        migrations.AddConstraint(
            model_name='thread',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('message__isnull', False), ('replying__isnull', False)), models.Q(('message__isnull', False), ('replying__isnull', True)), models.Q(
                ('message__isnull', True), ('replying__isnull', True)), _connector='OR'), name='thread_thread_message field can not be null in reply thread'),
        ),
    ]
