name: Django application

on:
  push:
    branches:
    - staging
    - master/*
  pull_request:
    branches:
    - staging
    - master/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: static Test
      run: |
        pre-commit run --all-files
        # mypy account APIV1
    - name: Unit Test
      run: |
        pytest --reuse-db --no-migrations
